# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-22 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('categorieId', models.CharField(max_length=20)),
                ('sort', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'categoriegroups',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='ChildGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('sort', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.CategorieGroup')),
            ],
            options={
                'db_table': 'childgroups',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='MainDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.CharField(max_length=20)),
                ('categoryName', models.CharField(max_length=40)),
                ('sort', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=200)),
                ('product1', models.CharField(max_length=20)),
                ('product2', models.CharField(max_length=20)),
                ('product3', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mainDescriptions',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longName', models.CharField(max_length=150)),
                ('productId', models.CharField(max_length=20)),
                ('storeNums', models.CharField(max_length=20)),
                ('specifics', models.CharField(max_length=20)),
                ('sort', models.CharField(max_length=20)),
                ('marketPrice', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('categoryId', models.CharField(max_length=20)),
                ('childId', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=100)),
                ('brandId', models.CharField(max_length=20)),
                ('brandName', models.CharField(max_length=100)),
                ('safeDay', models.CharField(max_length=20)),
                ('safeUnit', models.CharField(max_length=20)),
                ('safeUnitDesc', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=150)),
                ('sort', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'slideshows',
                'ordering': ['sort'],
            },
        ),
    ]
